# Generated by Django 3.0.5 on 2020-09-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200913_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='posts',
            new_name='post',
        ),
    ]
